import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import "yet-another-react-lightbox/styles.css";
import { QueryProvider } from "@/providers/query-provider";
import ProvidersClientWrapper from "@/components/providers/ProvidersClientWrapper";
import { getServerUser } from "@/lib/server";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    display: "swap", // Prevents flash of invisible text
});

// Keep Geist Mono for code/monospace elements if needed
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Fetch minimal user info on the server and pass it into the client providers wrapper.
    const serverUser = await getServerUser()

    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${geistMono.variable} antialiased font-inter`}
            >
                <NextTopLoader
                    color="#026993"
                    height={3}
                    showSpinner={false}
                    shadow="0 0 10px #026993,0 0 5px #026993"
                />
                <QueryProvider>
                    <ProvidersClientWrapper user={serverUser}>
                        {children}
                    </ProvidersClientWrapper>
                </QueryProvider>
                <Toaster
                    position="top-right"
                    expand={true}
                    richColors={true}
                />
            </body>
        </html>
    );
}
