import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import "yet-another-react-lightbox/styles.css";
import { QueryProvider } from "@/providers/query-provider";
import { AuthProvider } from "@/components/providers/AuthProvider";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    display: "swap", // Prevents flash of invisible text
});

// Keep Geist Mono for code/monospace elements if needed
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${geistMono.variable} antialiased font-inter`}
            >
                <QueryProvider>
                    <AuthProvider>
                        {children}
                    </AuthProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
